spring:

  application:
    name: ai-ticket-resolver

  ai:

    ollama:

      base-url: http://localhost:11434

      chat:
        options:
          model: llama3.2
          temperature: 0.1

      embedding:
        options:
          model: nomic-embed-text


server:
  port: 8080